# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_area_animation', models.BooleanField()),
                ('disable_overlapped_content', models.BooleanField()),
                ('mouse_click_lock', models.BooleanField()),
                ('mouse_sonar', models.BooleanField()),
                ('mouse_vanish', models.BooleanField()),
                ('screen_reader', models.BooleanField()),
                ('show_sounds', models.BooleanField()),
                ('focus_border_height', models.BigIntegerField(blank=True, null=True)),
                ('focus_border_width', models.BigIntegerField(blank=True, null=True)),
                ('message_duration', models.BigIntegerField(blank=True, null=True)),
                ('mouse_click_lock_time', models.BigIntegerField(blank=True, null=True)),
                ('high_contrast', models.CharField(blank=True, max_length=200, null=True)),
                ('audio_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
