# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20160406_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='audio_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='focus_border_height',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='focus_border_width',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='high_contrast',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='message_duration',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mouse_click_lock_time',
            field=models.BigIntegerField(),
        ),
    ]
