# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20160406_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='audio_description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='client_area_animation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disable_overlapped_content',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='focus_border_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='focus_border_width',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='high_contrast',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='message_duration',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mouse_click_lock',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mouse_click_lock_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mouse_vanish',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='screen_reader',
        ),
        migrations.AddField(
            model_name='profile',
            name='focus_border',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='magnifier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
