# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 20:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_profile_on_screen_keyboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='focus_border',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
    ]
