# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20160507_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='focus_border',
            field=models.IntegerField(default=1),
        ),
    ]
